name: ssh
on: [push]
jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
    - name: Clone xrd-tools repo
      run: git clone https://github.com/ios-xr/xrd-tools.git -b handle-dirty-docker-version
    - name: Host setup
      run: |
        sudo sysctl -w fs.inotify.max_user_instances=64000
        sudo sysctl -w net.core.netdev_max_backlog=300000
        sudo sysctl -w net.core.optmem_max=67108864
        sudo sysctl -w net.core.rmem_default=67108864
        sudo sysctl -w net.core.rmem_max=67108864
        sudo sysctl -w net.core.wmem_default=67108864
        sudo sysctl -w net.core.wmem_max=67108864
        sudo sysctl -w net.ipv4.udp_mem='1124736 10000000 67108864'
        sudo sysctl -w net.bridge.bridge-nf-call-iptables=0
        sudo sysctl -w net.bridge.bridge-nf-call-ip6tables=0
        # echo 3072 | sudo tee /proc/sys/vm/nr_hugepages
        sudo apt install -y apparmor-utils && sudo aa-teardown
    - name: Run host-check
      run: sudo ./xrd-tools/scripts/host-check -e docker xr-compose || true
    - name: Start upterm SSH session
      uses: lhotari/action-upterm@v1
